---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-registry-secret
type: kubernetes.io/dockerconfigjson
stringData:
  # Create a Deploy Token in GitLab (Settings -> Respository -> Exapand "Deploy tokens")
  # with "read_registry" capabilities. Put in a username, that you also put below. Put the
  # token as password below. For the auth value, run:
  # $ echo -n "username:password" | base 64
  # where you replace username and password for the respective values.
  .dockerconfigjson: |
    {
      "auths": {
        "gitlab.lrz.de:5005/ldv/teaching/ami/ami2023/projects/group03": {
          "username": "k8s",
          "password": "frqxo_gQwJESybkaevyY",
          "email": "hukumrajsingh.deora@tum.de",
          "auth": "azhzOmZycXhvX2dRd0pFU3lia2FldnlZ"
        }
      }
    }